### ISSUE TITLE
Callback on failure!

### ISSUE THREAD

**Issue by MindOver** [summera/chromestore.js#6]
Hi @summera 

Thankx for the API :+1: 

I'm might not know how to use it properly, but if I'm trying to get a file, how can I set a callback if the file does not exist, when the flag create is set to false?

``` javascript
cs.getFile('data/foo.txt', {create: false, exclusive: true}, function (fileEntry) {
        console.log('File created', fileEntry);
});
```

Cheers,

**Comment by HaNdTriX** [comment]
+1

**Comment by summera** [comment]
Been a long time since I've used this, but I'm assuming an error is logged to the console? Probably `NotFoundError`?

If you [look at the source](https://github.com/summera/chromestore.js/blob/master/chromestore.js#L206), you will see we just pass this call off to the filesystem. If you look at the [docs for the filesystem api](https://dev.w3.org/2009/dap/file-system/file-dir-sys.html#widl-DirectoryEntrySync-getFile-FileEntrySync-DOMString-path-Flags-options), it says: _If create is not true and the path doesn't exist, getFile must fail._

So I am guessing the `errorHandler` gets called. If so, we currently do not allow a custom `errorHandler` to be passed in, but I'm open to a pull request :smile:. If that's not the case, let me know what the actual result is and what you would like it to be.

**Comment by summera** [comment]
@HaNdTriX @MindOver going to close the issue. Let me know if you have any other questions
